#if UNITY_EDITOR
using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

using SHUU.Utils.InputSystem;
using SHUU.Utils.Data;
using SHUU.InnerWorkings.Preferences;

using static SHUU.Utils.Helpers.HandyFunctions;

using SETB.SuperClasses;

using static SETB.EditorHelpers;
using static SETB.EditorGUI_Base;

namespace SHUU._Editor.CodeGeneration
{
    public class InputSystem_StaticReferencesGenerator : EditorWindow_Base<InputSystem_StaticReferencesGenerator>
    {
        #region Variables
        private const string fileSuffix = "_GeneratedStaticReferences";

        private static string DefaultFilePath => SHUUPreferences_InputSystem.Instance?.codeGeneration_assetPath;



        private InputActionAsset asset;
        #endregion




        #region Main
        [MenuItem("Tools/Sprout's Handy Unity Utils/Input System/Regenerate Static References")]
        public static void ShowWindow() => CreateWindow("Input System Static References Generator", centered: true, minWidth: 360, minHeight: 200).asset = SHUU_Input.InputActionAsset;


        private void OnGUI()
        {
            DrawInputObject("Input Action Asset", ref asset, false);

			FlexibleSpace();

			DrawButton("Generate for all Assets", () => Generate(), options: GUILayout.Height(28));

			Space(3f);

			using (new EditorGUI.DisabledScope(asset == null))
				DrawButton("Generate for selected Asset", () => GenerateForAsset(asset), options: GUILayout.Height(28));
        }
        #endregion



        #region Logic

        #region Generate
        private void Generate()
        {
            foreach (var asset in EnumerateAssets<InputActionAsset>())
                GenerateForAsset(asset);
        }

        private void GenerateForAsset(InputActionAsset asset)
        {
            if (asset == null || string.IsNullOrWhiteSpace(asset.name)) return;

            string fileName = SanitizeIdentifier(asset.name) + fileSuffix;
            string filePath = ResolveFilePath(DefaultFilePath, fileName);

            DataManager.EnsureDirectoryExists(filePath);

            File.WriteAllText(filePath, BuildFile(asset), new UTF8Encoding(false));

            AssetDatabase.ImportAsset(filePath);
            AssetDatabase.Refresh();
            Debug.Log($"Input System Static References generated for '{asset.name}':\n{filePath}");
        }


        private static string ResolveFilePath(string assetPath, string fileName)
        {
            foreach (var (_, path) in EnumerateAssetsWithPath<MonoScript>(fileName))
                if (string.Equals(Path.GetFileNameWithoutExtension(path), fileName, StringComparison.Ordinal)) return path;

            return Path.Combine(Path.GetDirectoryName(assetPath), fileName + ".cs");
        }
        #endregion

        

        #region Code Generation

        #region Build
        private static string BuildFile(InputActionAsset asset)
        {
            string className = SanitizeIdentifier(asset.name) + "_Input";

            var sb = new StringBuilder();


            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was auto-generated by the SHUU Input System.");
            sb.AppendLine("// Do not edit manually — changes will be overwritten on next generation.");
            sb.AppendLine("// </auto-generated>");

            sb.AppendLine();
            sb.AppendLine();

            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.InputSystem;");
            sb.AppendLine();
            sb.AppendLine("using SHUU.Utils.InputSystem;");

            sb.AppendLine();
            
            sb.AppendLine($"public static class {className}");
            sb.AppendLine("{");
            sb.Append(BuildCode(asset, 1));
            sb.AppendLine("}");

            sb.AppendLine();
            AppendExtensions(sb, asset, className, 0);

            return sb.ToString();
        }


        private static string BuildCode(InputActionAsset asset, int baseIndent = 0)
        {
            var sb = new StringBuilder();


            #region Header
            sb.AppendLine($"{Indent(baseIndent)}#region Header");
            sb.AppendLine();

            AppendControlSchemeEnum(sb, asset, baseIndent);

            sb.AppendLine();
            sb.AppendLine();

            AppendActionMapEnum(sb, asset, baseIndent);

            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();

            AppendActionMapsHelper(sb, asset, baseIndent);

            sb.AppendLine();
            sb.AppendLine($"{Indent(baseIndent)}#endregion");
            #endregion


            #region Spacing
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();
            #endregion


            #region Body
            sb.AppendLine($"{Indent(baseIndent)}#region Body");
            sb.AppendLine();

            bool firstMap = true;
            foreach (var map in asset.actionMaps)
            {
                if (!firstMap)
                {
                    sb.AppendLine();
                    sb.AppendLine();
                    sb.AppendLine();
                    sb.AppendLine();
                }
                else firstMap = false;

                AppendMap(sb, map, baseIndent);
            }

            sb.AppendLine();
            sb.AppendLine($"{Indent(baseIndent)}#endregion");
            #endregion


            return sb.ToString();
        }
        #endregion



        #region Header
        private static void AppendControlSchemeEnum(StringBuilder sb, InputActionAsset asset, int indentLevel)
        {
            string indent = Indent(indentLevel);
            string innerIndent = Indent(indentLevel + 1);


            #region ControlScheme enum
            sb.AppendLine($"{indent}#region ControlScheme enum");

            sb.AppendLine($"{indent}public enum ControlScheme");
            sb.AppendLine($"{indent}{{");

            foreach (var scheme in asset.controlSchemes)
                sb.AppendLine($"{innerIndent}{SanitizeIdentifier(scheme.name)},");

            sb.AppendLine($"{indent}}}");

            sb.AppendLine($"{indent}#endregion");
            #endregion
        }

        private static void AppendActionMapEnum(StringBuilder sb, InputActionAsset asset, int indentLevel)
        {
            string indent = Indent(indentLevel);
            string innerIndent = Indent(indentLevel + 1);


            #region ActionMap enum
            sb.AppendLine($"{indent}#region ActionMap enum");

            sb.AppendLine($"{indent}public enum ActionMapID");
            sb.AppendLine($"{indent}{{");

            foreach (var map in asset.actionMaps)
                sb.AppendLine($"{innerIndent}{SanitizeIdentifier(map.name)},");

            sb.AppendLine($"{indent}}}");

            sb.AppendLine($"{indent}#endregion");
            #endregion
        }


        private static void AppendExtensions(StringBuilder sb, InputActionAsset asset, string outerClass, int indentLevel)
        {
            string indent = Indent(indentLevel);
            string innerIndent = Indent(indentLevel + 1);

            string csType = $"{outerClass}.ControlScheme";
            string amType = $"{outerClass}.ActionMapID";

            sb.AppendLine($"{indent}public static class {outerClass}_ControlSchemeExtensions");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{innerIndent}public static string ToSchemeName(this {csType} scheme)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    return scheme switch");
            sb.AppendLine($"{innerIndent}    {{");

            foreach (var scheme in asset.controlSchemes)
                sb.AppendLine($"{innerIndent}        {csType}.{SanitizeIdentifier(scheme.name)} => \"{EscapeString(scheme.name)}\",");

            sb.AppendLine($"{innerIndent}        _ => null");
            sb.AppendLine($"{innerIndent}    }};");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{indent}}}");

            sb.AppendLine();

            sb.AppendLine($"{indent}public static class {outerClass}_ActionMapIDExtensions");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{innerIndent}public static string ToMapName(this {amType} map)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    return map switch");
            sb.AppendLine($"{innerIndent}    {{");

            foreach (var map in asset.actionMaps)
                sb.AppendLine($"{innerIndent}        {amType}.{SanitizeIdentifier(map.name)} => \"{EscapeString(map.name)}\",");

            sb.AppendLine($"{innerIndent}        _ => null");
            sb.AppendLine($"{innerIndent}    }};");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{indent}}}");
        }


        private static void AppendActionMapsHelper(StringBuilder sb, InputActionAsset asset, int indentLevel)
        {
            string indent = Indent(indentLevel);
            string innerIndent = Indent(indentLevel + 1);


            #region ActionMaps class
            sb.AppendLine($"{indent}public static class ActionMaps");
            sb.AppendLine($"{indent}{{");


            #region General
            sb.AppendLine($"{innerIndent}#region General");

            sb.AppendLine($"{innerIndent}private static string[] ToNames(ActionMapID[] maps)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    string[] names = new string[maps.Length];");
            sb.AppendLine($"{innerIndent}    for (int i = 0; i < maps.Length; i++)");
            sb.AppendLine($"{innerIndent}       names[i] = maps[i].ToMapName();");
            sb.AppendLine($"{innerIndent}    return names;");
            sb.AppendLine($"{innerIndent}}}");

            sb.AppendLine();

            sb.AppendLine($"{innerIndent}private static ActionMapID? NameToID(string mapName)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    return mapName switch");
            sb.AppendLine($"{innerIndent}    {{");

            foreach (var map in asset.actionMaps)
                sb.AppendLine($"{innerIndent}        \"{EscapeString(map.name)}\" => ActionMapID.{SanitizeIdentifier(map.name)},");

            sb.AppendLine($"{innerIndent}        _ => null");
            sb.AppendLine($"{innerIndent}    }};");
            sb.AppendLine($"{innerIndent}}}");

            sb.AppendLine($"{innerIndent}#endregion");
            #endregion

            sb.AppendLine();
            sb.AppendLine();

            #region Global (SHUU_Input)
            sb.AppendLine($"{innerIndent}#region Global (SHUU_Input)");

            // Enable/Disable one or more maps by enum
            sb.AppendLine($"{innerIndent}// Enable/Disable one or more maps by enum");
            sb.AppendLine($"{innerIndent}public static void Enable(params ActionMapID[] maps) => SHUU_Input.EnableMaps(ToNames(maps));");
            sb.AppendLine($"{innerIndent}public static void Disable(params ActionMapID[] maps) => SHUU_Input.DisableMaps(ToNames(maps));");
            sb.AppendLine($"{innerIndent}public static void EnableMapsDisableRest(params ActionMapID[] maps) => SHUU_Input.EnableMapsDisableRest(ToNames(maps));");
            sb.AppendLine($"{innerIndent}public static void DisableMapsEnableRest(params ActionMapID[] maps) => SHUU_Input.DisableMapsEnableRest(ToNames(maps));");
            sb.AppendLine();

            // Context stack by enum
            sb.AppendLine($"{innerIndent}// Global (SHUU_Input) — context stack by enum");
            sb.AppendLine($"{innerIndent}public static void PushContext(ActionMapID map) => SHUU_Input.PushContext(map.ToMapName());");
            sb.AppendLine($"{innerIndent}public static ActionMapID? PopContext()");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    string popped = SHUU_Input.PopContext();");
            sb.AppendLine($"{innerIndent}    return popped == null ? null : NameToID(popped);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static ActionMapID? PeekContext()");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    string current = SHUU_Input.PeekContext();");
            sb.AppendLine($"{innerIndent}    return current == null ? null : NameToID(current);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void ClearContext() => SHUU_Input.ClearContext();");
            sb.AppendLine($"{innerIndent}public static int ContextDepth() => SHUU_Input.ContextDepth;");

            sb.AppendLine($"{innerIndent}#endregion");
            #endregion

            sb.AppendLine();
            sb.AppendLine();

            #region Per-player (SHUU_PlayerInput)
            sb.AppendLine($"{innerIndent}#region Per-player (SHUU_PlayerInput)");

            // Enable/Disable one or more maps by enum for a specific player
            sb.AppendLine($"{innerIndent}// Enable/Disable one or more maps by enum for a specific player");
            sb.AppendLine($"{innerIndent}public static void Enable(SHUU_PlayerInput player, params ActionMapID[] maps) => player.EnableMaps(ToNames(maps));");
            sb.AppendLine($"{innerIndent}public static void Disable(SHUU_PlayerInput player, params ActionMapID[] maps) => player.DisableMaps(ToNames(maps));");
            sb.AppendLine($"{innerIndent}public static void EnableMapsDisableRest(SHUU_PlayerInput player, params ActionMapID[] maps) => player.EnableMapsDisableRest(ToNames(maps));");
            sb.AppendLine($"{innerIndent}public static void DisableMapsEnableRest(SHUU_PlayerInput player, params ActionMapID[] maps) => player.DisableMapsEnableRest(ToNames(maps));");
            sb.AppendLine();

            // Context stack by enum
            sb.AppendLine($"{innerIndent}// Context stack by enum");
            sb.AppendLine($"{innerIndent}public static void PushContext(SHUU_PlayerInput player, ActionMapID map) => player.PushContext(map.ToMapName());");
            sb.AppendLine($"{innerIndent}public static ActionMapID? PopContext(SHUU_PlayerInput player)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    string popped = player.PopContext();");
            sb.AppendLine($"{innerIndent}    return popped == null ? null : NameToID(popped);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static ActionMapID? PeekContext(SHUU_PlayerInput player)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    string current = player.PeekContext();");
            sb.AppendLine($"{innerIndent}    return current == null ? null : NameToID(current);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void ClearContext(SHUU_PlayerInput player) => player.ClearContext();");
            sb.AppendLine($"{innerIndent}public static int ContextDepth(SHUU_PlayerInput player) => player.contextDepth;");

            sb.AppendLine($"{innerIndent}#endregion");
            #endregion


            sb.AppendLine($"{indent}}}");
            #endregion
        }
        #endregion



        #region Body
        private static void AppendMap(StringBuilder sb, InputActionMap map, int indentLevel)
        {
            string indent = Indent(indentLevel);
            string innerIndent = Indent(indentLevel + 1);

            string mapId = SanitizeIdentifier(map.name) + "_Input";


            #region Map class
            sb.AppendLine($"{indent}#region {map.name} Map");

            sb.AppendLine($"{indent}public static class {mapId}");
            sb.AppendLine($"{indent}{{");

            #region Header
            sb.AppendLine($"{innerIndent}#region Header");

            sb.AppendLine($"{innerIndent}public const string mapName = \"{EscapeString(map.name)}\";");
            sb.AppendLine($"{innerIndent}public const ActionMapID mapID = ActionMapID.{SanitizeIdentifier(map.name)};");

            sb.AppendLine();
            sb.AppendLine();

            sb.AppendLine($"{innerIndent}public static bool IsEnabled(SHUU_PlayerInput player = null) => player != null ? player.IsMapEnabled(mapName) : SHUU_Input.IsMapEnabled(mapName);");

            sb.AppendLine();

            sb.AppendLine($"{innerIndent}public static void Enable(SHUU_PlayerInput player = null) {{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.EnableMap(mapName);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.EnableMap(mapName);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void Disable(SHUU_PlayerInput player = null) {{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.DisableMap(mapName);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.DisableMap(mapName);");
            sb.AppendLine($"{innerIndent}}}");

            sb.AppendLine($"{innerIndent}#endregion");
            #endregion
            
            sb.AppendLine();
            sb.AppendLine();
            sb.AppendLine();

            #region Actions
            sb.AppendLine($"{innerIndent}#region Actions");

            sb.AppendLine();

            bool firstAction = true;
            foreach (var action in map.actions)
            {
                if (!firstAction)
                {
                    sb.AppendLine();
                    sb.AppendLine();
                }
                else firstAction = false;
                    
                AppendAction(sb, map, action, indentLevel + 1);
            }

            sb.AppendLine();

            sb.AppendLine($"{innerIndent}#endregion");
            #endregion

            sb.AppendLine($"{indent}}}");

            sb.AppendLine($"{indent}#endregion");
            #endregion
        }


        private static void AppendAction(StringBuilder sb, InputActionMap map, InputAction action, int indentLevel)
        {
            string indent = Indent(indentLevel);
            string innerIndent = Indent(indentLevel + 1);

            string actionId = SanitizeIdentifier(action.name);
            string actionPath = $"{map.name}/{action.name}";

            bool isVector2 = string.Equals(action.expectedControlType, "Vector2", StringComparison.OrdinalIgnoreCase);
            string valueType = isVector2 ? "Vector2" : "float";
            string valueGetter = isVector2 ? "GetInputValue2D" : "GetInputValue";


            #region Action class
            sb.AppendLine($"{indent}#region {action.name} Action");

            sb.AppendLine($"{indent}public static class {actionId}");
            sb.AppendLine($"{indent}{{");

            // Path constant
            sb.AppendLine($"{innerIndent}public const string path = \"{EscapeString(actionPath)}\";");

            sb.AppendLine();
            sb.AppendLine();

            #region Fetch
            sb.AppendLine($"{innerIndent}#region Fetch");

            sb.AppendLine($"{innerIndent}public static bool Get(SHUU_PlayerInput player = null) => player != null ? player.GetInput(path) : SHUU_Input.GetInput(path);");
            sb.AppendLine($"{innerIndent}public static bool GetDown(SHUU_PlayerInput player = null) => player != null ? player.GetInputDown(path) : SHUU_Input.GetInputDown(path);");
            sb.AppendLine($"{innerIndent}public static bool GetUp(SHUU_PlayerInput player = null) => player != null ? player.GetInputUp(path) : SHUU_Input.GetInputUp(path);");
            sb.AppendLine();
            sb.AppendLine($"{innerIndent}public static {valueType} GetValue(SHUU_PlayerInput player = null) => player != null ? player.{valueGetter}(path) : SHUU_Input.{valueGetter}(path);");
            
            sb.AppendLine($"{innerIndent}#endregion");
            #endregion
            
            sb.AppendLine();
            sb.AppendLine();

            #region Buffering
            sb.AppendLine($"{innerIndent}#region Buffering");
            sb.AppendLine($"{innerIndent}public static void RegisterBufferInput_Down(float bufferTime = 0.15f, bool ignoreTimeScale = false, SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.RegisterBufferInput_Down(path, bufferTime, ignoreTimeScale);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.RegisterBufferInput_Down(path, bufferTime, ignoreTimeScale);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void UnregisterBufferInput_Down(SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.UnregisterBufferInput_Down(path);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.UnregisterBufferInput_Down(path);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static bool GetBufferedInput_Down(bool consume = true, SHUU_PlayerInput player = null) => player != null ? player.GetBufferedInput_Down(path, consume) : SHUU_Input.GetBufferedInput_Down(path, consume);");
            
            sb.AppendLine();

            sb.AppendLine($"{innerIndent}public static void RegisterBufferInput_Up(float bufferTime = 0.15f, bool ignoreTimeScale = false, SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.RegisterBufferInput_Up(path, bufferTime, ignoreTimeScale);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.RegisterBufferInput_Up(path, bufferTime, ignoreTimeScale);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void UnregisterBufferInput_Up(SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.UnregisterBufferInput_Up(path);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.UnregisterBufferInput_Up(path);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static bool GetBufferedInput_Up(bool consume = true, SHUU_PlayerInput player = null) => player != null ? player.GetBufferedInput_Up(path, consume) : SHUU_Input.GetBufferedInput_Up(path, consume);");
            
            sb.AppendLine($"{innerIndent}#endregion");
            #endregion

            sb.AppendLine();
            sb.AppendLine();

            #region Listeners
            sb.AppendLine($"{innerIndent}#region Listeners");

            sb.AppendLine($"{innerIndent}public static void RegisterListener_Down(Action callback, SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.RegisterListener_Down(path, callback);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.RegisterListener_Down(path, callback);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void UnregisterListener_Down(Action callback, SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.UnregisterListener_Down(path, callback);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.UnregisterListener_Down(path, callback);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void UnregisterListener_Down(SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.UnregisterListener_Down(path);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.UnregisterListener_Down(path);");
            sb.AppendLine($"{innerIndent}}}");

            sb.AppendLine();

            sb.AppendLine($"{innerIndent}public static void RegisterListener_Up(Action callback, SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.RegisterListener_Up(path, callback);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.RegisterListener_Up(path, callback);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void UnregisterListener_Up(Action callback, SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.UnregisterListener_Up(path, callback);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.UnregisterListener_Up(path, callback);");
            sb.AppendLine($"{innerIndent}}}");
            sb.AppendLine($"{innerIndent}public static void UnregisterListener_Up(SHUU_PlayerInput player = null)");
            sb.AppendLine($"{innerIndent}{{");
            sb.AppendLine($"{innerIndent}    if (player != null) player.UnregisterListener_Up(path);");
            sb.AppendLine($"{innerIndent}    else SHUU_Input.UnregisterListener_Up(path);");
            sb.AppendLine($"{innerIndent}}}");

            sb.AppendLine($"{innerIndent}#endregion");
            #endregion

            sb.AppendLine();
            sb.AppendLine();

            #region Prompts
            sb.AppendLine($"{innerIndent}#region Prompts");

            sb.AppendLine($"{innerIndent}public static string GetPrompt(string schemeName, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayString(path, schemeName) : SHUU_Input.GetBindingDisplayString(path, schemeName);");
            sb.AppendLine($"{innerIndent}public static string GetPrompt(ControlScheme scheme, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayString(path, scheme.ToSchemeName()) : SHUU_Input.GetBindingDisplayString(path, scheme.ToSchemeName());");
            sb.AppendLine($"{innerIndent}public static string GetPrompt(string schemeName, int schemeBindingIndex, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayString(path, schemeName, schemeBindingIndex) : SHUU_Input.GetBindingDisplayString(path, schemeName, schemeBindingIndex);");
            sb.AppendLine($"{innerIndent}public static string GetPrompt(ControlScheme scheme, int schemeBindingIndex, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayString(path, scheme.ToSchemeName(), schemeBindingIndex) : SHUU_Input.GetBindingDisplayString(path, scheme.ToSchemeName(), schemeBindingIndex);");
            
            sb.AppendLine();
            
            // Absolute binding index (across all schemes)
            sb.AppendLine($"{innerIndent}// Absolute binding index (across all schemes)");
            sb.AppendLine($"{innerIndent}public static string GetPrompt(int bindingIndex, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayString(path, bindingIndex) : SHUU_Input.GetBindingDisplayString(path, bindingIndex);");
            sb.AppendLine($"{innerIndent}public static List<string> GetPrompts(string schemeName, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayStrings(path, schemeName) : SHUU_Input.GetBindingDisplayStrings(path, schemeName);");
            sb.AppendLine($"{innerIndent}public static List<string> GetPrompts(ControlScheme scheme, SHUU_PlayerInput player = null) => player != null ? player.GetBindingDisplayStrings(path, scheme.ToSchemeName()) : SHUU_Input.GetBindingDisplayStrings(path, scheme.ToSchemeName());");
            sb.AppendLine($"{innerIndent}public static Dictionary<int, string> GetAllPrompts(SHUU_PlayerInput player = null) => player != null ? player.GetAllBindingDisplayStrings(path) : SHUU_Input.GetAllBindingDisplayStrings(path);");

            sb.AppendLine();

            // Player-only — uses the player's CURRENT control scheme automatically.
            sb.AppendLine($"{innerIndent}// Player-only — uses the player's CURRENT control scheme automatically.");
            sb.AppendLine($"{innerIndent}public static string GetPrompt(SHUU_PlayerInput player) => player.GetBindingDisplayString(path);");
            sb.AppendLine($"{innerIndent}public static string GetPromptInScheme(SHUU_PlayerInput player, int schemeBindingIndex) => player.GetBindingDisplayStringInScheme(path, schemeBindingIndex);");
            
            sb.AppendLine($"{innerIndent}#endregion");
            #endregion

            sb.AppendLine();
            sb.AppendLine();

            sb.AppendLine($"{innerIndent}public static int GetCompositePartBindingIndex(CompositeBindPart part, SHUU_PlayerInput player = null) => player != null ? player.GetCompositePartBindingIndex(path, part) : SHUU_Input.GetCompositePartBindingIndex(path, part);");
            sb.AppendLine($"{innerIndent}public static int GetCompositePartBindingIndex(string partName, SHUU_PlayerInput player = null) => player != null ? player.GetCompositePartBindingIndex(path, partName) : SHUU_Input.GetCompositePartBindingIndex(path, partName);");

            sb.AppendLine($"{indent}}}");

            sb.AppendLine($"{indent}#endregion");
            #endregion
        }
        #endregion
        


        #region Helpers
        private static string Indent(int level) => new string(' ', level * 4);

        private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        #endregion

        #endregion

        #endregion
    }
}
#endif
