#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System.Text;
using System;
using System.IO;

using SHUU.Utils.SettingsSystem;
using SHUU.Utils.Data;
using SHUU.InnerWorkings.Preferences;

using static SHUU.InnerWorkings.SHUU_PackageUtils;
using static SHUU.Utils.Helpers.HandyFunctions;

using SETB.SuperClasses;

using static SETB.EditorHelpers;
using static SETB.EditorGUI_Base;

namespace SHUU._Editor.CodeGeneration
{
	public class SettingsSystem_StaticReferencesGenerator : EditorWindow_Base<SettingsSystem_StaticReferencesGenerator>
	{
	    #region Variables
		private const string fileSuffix = "_GeneratedStaticReferences";

		private static string DefaultFilePath => SHUUPreferences_SettingsSystem.Instance?.codeGeneration_assetPath;



		private SettingsAtlas atlas;
		#endregion




		#region Main
		[MenuItem("Tools/Sprout's Handy Unity Utils/Settings System/Regenerate Static References")]
		public static void ShowWindow() => CreateWindow("Settings System Static References Generator", centered: true, minWidth: 360, minHeight: 200).atlas = SettingsAtlas.DefaultAtlas;


		protected void OnGUI()
		{
			DrawInputObject("Settings Atlas", ref atlas, false);

			FlexibleSpace();

			DrawButton("Generate for all Atlases", () => Generate(), options: GUILayout.Height(28));

			Space(3f);

			using (new EditorGUI.DisabledScope(atlas == null))
				DrawButton("Generate for selected Atlas", () => GenerateForAtlas(atlas), options: GUILayout.Height(28));
		}
		#endregion




		#region Logic

		#region Generate
		public static void Generate()
		{
			foreach (var atlas in EnumerateAssets<SettingsAtlas>())
				GenerateForAtlas(atlas);
		}

		public static void GenerateForAtlas(SettingsAtlas atlas)
		{
			if (atlas == null || string.IsNullOrWhiteSpace(atlas.settingsName)) return;

			TrackScriptableObject(atlas);

			string fileName = SanitizeIdentifier(atlas.name) + fileSuffix;
			string filePath = ResolveFilePath(DefaultFilePath, fileName);

			DataManager.EnsureDirectoryExists(filePath);

			File.WriteAllText(filePath, BuildFile(atlas), new UTF8Encoding(false));

			AssetDatabase.ImportAsset(filePath);
            AssetDatabase.Refresh();
			Debug.Log($"Settings System Static References generated for '{atlas.name}':\n{filePath}");
		}


		private static string ResolveFilePath(string defaultPath, string fileName)
		{
			foreach (var (_, path) in EnumerateAssetsWithPath<MonoScript>(fileName))
				if (string.Equals(Path.GetFileNameWithoutExtension(path), fileName, StringComparison.Ordinal)) return path;

			return Path.Combine(defaultPath, fileName + ".cs");
		}
		#endregion



		#region Code Generation

		#region Build
		private static string BuildFile(SettingsAtlas atlas)
		{
			string className = SanitizeIdentifier(atlas.settingsName) + "_Settings";

			var sb = new StringBuilder();


			sb.AppendLine("// <auto-generated>");
			sb.AppendLine("// This file was auto-generated by SHUU Settings System.");
			sb.AppendLine("// Do not edit manually — changes will be overwritten on next generation.");
			sb.AppendLine("// </auto-generated>");

			sb.AppendLine();
			sb.AppendLine();

			sb.AppendLine("using SHUU.Utils.SettingsSystem;");

			sb.AppendLine();

			sb.AppendLine("namespace SHUU.Utils.SettingsSystem");
			sb.AppendLine("{");

			sb.AppendLine($"{Indent(1)}public static class {className}");
			sb.AppendLine(Indent(1) + "{");

			sb.Append(BuildCode(atlas, 2));

			sb.AppendLine(Indent(1) + "}");

			sb.AppendLine("}");


			return sb.ToString();
		}

		private static string BuildCode(SettingsAtlas atlas, int baseIndent = 0)
		{
			string i0 = Indent(baseIndent);
			string i1 = Indent(baseIndent + 1);
			string i2 = Indent(baseIndent + 2);

			var sb = new StringBuilder();

			
			sb.AppendLine($"{i0}private static SettingsAtlas asset => SettingsAtlas.GetSettingsAtlas(\"{EscapeString(atlas.settingsName)}\");");

			sb.AppendLine();

			#region Maps
			foreach (var map in atlas.maps)
			{
				if (string.IsNullOrWhiteSpace(map.mapName)) continue;

				string mapClassName = SanitizeIdentifier(map.mapName);


				sb.AppendLine();
				sb.AppendLine();
				sb.AppendLine();
				
				sb.AppendLine($"{i0}#region {mapClassName}");

				sb.AppendLine($"{i0}public static class {mapClassName}");
				sb.AppendLine($"{i0}{{");

				sb.AppendLine($"{i1}private static SettingMap map => asset.GetMap(\"{EscapeString(map.mapName)}\");");

				sb.AppendLine();

				foreach (var field in map.fields)
				{
					if (string.IsNullOrWhiteSpace(field.key)) continue;

					sb.AppendLine();

					sb.AppendLine(GenerateProperty(field, i1, "map"));
				}

				#region Groups
				foreach (var group in map.groups)
				{
					if (string.IsNullOrWhiteSpace(group.groupName)) continue;

					string groupClassName = SanitizeIdentifier(group.groupName);


					sb.AppendLine();

					sb.AppendLine($"{i1}#region {groupClassName}");

					sb.AppendLine($"{i1}public static class {groupClassName}");
					sb.AppendLine($"{i1}{{");

					sb.AppendLine($"{i2}private static SettingGroup group => map.GetGroup(\"{EscapeString(group.groupName)}\");");

					sb.AppendLine();

					foreach (var field in group.fields)
					{
						if (string.IsNullOrWhiteSpace(field.key)) continue;

						sb.AppendLine(GenerateProperty(field, i2, "group"));
					}

					sb.AppendLine($"{i1}}}");

					sb.AppendLine($"{i1}#endregion");
				}
				#endregion

				sb.AppendLine($"{i0}}}");

				sb.AppendLine($"{i0}#endregion");
			}
			#endregion


			return sb.ToString();
		}
		#endregion



		#region Generate
		private static string GenerateProperty(SettingField field, string indent, string accessor)
		{
			string key = SanitizeIdentifier(field.key);
			string escapedKey = EscapeString(field.key);

			switch (field.type)
			{
				case SettingType.Bool:
					return GenerateProperty(
						"bool",
						key,
						$"{accessor}.GetBool(\"{escapedKey}\")",
						$"{accessor}.SetBool(\"{escapedKey}\", value)",
						indent);

				case SettingType.Int:
					return GenerateProperty(
						"int",
						key,
						$"{accessor}.GetInt(\"{escapedKey}\")",
						$"{accessor}.SetInt(\"{escapedKey}\", value)",
						indent);

				case SettingType.Float:
					return GenerateProperty(
						"float",
						key,
						$"{accessor}.GetFloat(\"{escapedKey}\")",
						$"{accessor}.SetFloat(\"{escapedKey}\", value)",
						indent);

				case SettingType.String:
					return GenerateProperty(
						"string",
						key,
						$"{accessor}.GetString(\"{escapedKey}\")",
						$"{accessor}.SetString(\"{escapedKey}\", value)",
						indent);

				case SettingType.Enum:
					return GenerateEnumProperty(field, indent, accessor);

				default:
					return "";
			}
		}

		private static string GenerateProperty(string type, string propertyName, string getter, string setter, string indent)
		{
			var sb = new StringBuilder();

			sb.AppendLine($"{indent}public static {type} {propertyName}");
			sb.AppendLine($"{indent}{{");
			sb.AppendLine($"{indent}	get => {getter};");
			sb.AppendLine($"{indent}    set => {setter};");
			sb.Append($"{indent}}}");

			return sb.ToString();
		}


		private static string GenerateEnumProperty(SettingField field, string indent, string accessor)
		{
			Type enumType = null;
			if (!string.IsNullOrWhiteSpace(field.enumTypeName))
			{
				enumType = Type.GetType(field.enumTypeName);
				if (enumType == null)
				{
					foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
					{
						enumType = asm.GetType(field.enumTypeName);
						if (enumType != null) break;
					}
				}
			}


			string key = SanitizeIdentifier(field.key);
			string escapedKey = EscapeString(field.key);

			if (enumType != null && enumType.IsEnum)
			{
				string typeName = enumType.FullName.Replace('+', '.');

				return GenerateProperty(
					typeName,
					key,
					$"{accessor}.GetEnum<{typeName}>(\"{escapedKey}\")",
					$"{accessor}.SetEnum(\"{escapedKey}\", value)",
					indent);
			}

			var sb = new StringBuilder();

			sb.AppendLine($"{indent}// ⚠️ Enum type \"{field.enumTypeName}\" could not be resolved at generation time.");
			sb.AppendLine($"{indent}// Falling back to int. Re-run generation once the type is accessible.");
			sb.Append(
				GenerateProperty(
					"int",
					key,
					$"{accessor}.GetEnumInt(\"{escapedKey}\")",
					$"{accessor}.SetEnumInt(\"{escapedKey}\", value)",
					indent));

			return sb.ToString();
		}
		#endregion



		#region Helpers
		private static string Indent(int level) => new string(' ', level * 4);

		private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
		#endregion

		#endregion

		#endregion
	}
}
#endif
