#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

using SHUU.UserSide.Addons.AudioSystem.Preferences;
using SHUU.UserSide.Addons.AudioSystem.ScriptableObjects;
using SHUU.Utils.Data;

using static SHUU.Utils.Helpers.HandyFunctions;

using SETB.SuperClasses;

using static SETB.EditorHelpers;
using static SETB.EditorGUI_Base;

namespace SHUU.UserSide.Addons.AudioSystem._Editor
{
    public class AudioSystem_StaticReferencesGenerator : EditorWindow_Base<AudioSystem_StaticReferencesGenerator>
    {
        #region Variables
		private const string fileSuffix = "_GeneratedStaticReferences";

		private static string DefaultFilePath => SHUUPreferences_AudioSystem.Instance?.codeGeneration_assetPath;



		private AudioChannelGroup channelGroup;
		#endregion
    
    
    
    
        #region Main
		[MenuItem("Tools/Sprout's Handy Unity Utils/Audio System/Regenerate Static References")]
		public static void ShowWindow() => CreateWindow("Settings System Static References Generator", centered: true, minWidth: 360, minHeight: 200);


		protected void OnGUI()
		{
			DrawInputObject("Audio Channel Group", ref channelGroup, false);

			FlexibleSpace();

			DrawButton("Generate for all Channel Groups", () => Generate(), options: GUILayout.Height(28));

			Space(3f);

			using (new EditorGUI.DisabledScope(channelGroup == null))
				DrawButton("Generate for selected Channel Group", () => GenerateForGroup(channelGroup), options: GUILayout.Height(28));
		}
		#endregion



        #region Logic

        #region Generate
		public static void Generate()
		{
			foreach (var group in EnumerateAssets<AudioChannelGroup>())
				GenerateForGroup(group);
		}

		public static void GenerateForGroup(AudioChannelGroup group)
		{
			if (group == null || string.IsNullOrWhiteSpace(group.name)) return;


            ChannelInfo root = BuildChannelTree(group, "");


            string fileName = SanitizeIdentifier(group.name) + fileSuffix;
			string filePath = ResolveFilePath(DefaultFilePath, fileName);

			DataManager.EnsureDirectoryExists(filePath);

			File.WriteAllText(filePath, BuildFile(root), new UTF8Encoding(false));

			AssetDatabase.ImportAsset(filePath);
            AssetDatabase.Refresh();
			Debug.Log($"Settings System Static References generated for '{(group as IAudioChannel).GetID()}':\n{filePath}");
		}


		private static string ResolveFilePath(string defaultPath, string fileName)
		{
			foreach (var (_, path) in EnumerateAssetsWithPath<MonoScript>(fileName))
				if (string.Equals(Path.GetFileNameWithoutExtension(path), fileName, StringComparison.Ordinal)) return path;

			return Path.Combine(defaultPath, fileName + ".cs");
		}
		#endregion



        #region Prep
        private static ChannelInfo BuildChannelTree(IAudioChannel channel, string parentPath)
        {
            var info = new ChannelInfo
            {
                ID = channel.GetID(),
                Path = string.IsNullOrEmpty(parentPath) ? channel.GetID() : $"{parentPath}/{channel.GetID()}"
            };

            foreach (var child in channel.GetChildren())
                info.Children.Add(BuildChannelTree(child, info.Path));

            return info;
        }
        #endregion



        #region Code Generation

        #region Build
        private static string BuildFile(ChannelInfo root)
        {
            var sb = new StringBuilder();


            sb.AppendLine("// <auto-generated>");
			sb.AppendLine("// This file was auto-generated by SHUU Audio System.");
			sb.AppendLine("// Do not edit manually — changes will be overwritten on next generation.");
			sb.AppendLine("// </auto-generated>");

            sb.AppendLine();
            sb.AppendLine();

            sb.AppendLine("using UnityEngine;");

            sb.AppendLine();

            sb.AppendLine("using SHUU.UserSide.Addons.AudioSystem.ScriptableObjects;");
            sb.AppendLine("using SHUU.Utils.Helpers;");

            sb.AppendLine();

            sb.AppendLine("namespace SHUU.UserSide.Addons.AudioSystem");
            sb.AppendLine("{");
            sb.AppendLine(Indent(1) + "public partial class SHUU_AudioChannels");
            sb.AppendLine(Indent(1) + "{");

            BuildChannelClass(sb, root, 2);

            sb.AppendLine(Indent(1) + "}");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void BuildChannelClass(StringBuilder sb, ChannelInfo channel, int indentLevel)
        {
            string className = SanitizeIdentifier(channel.ID);
            int bl = indentLevel + 1;


            sb.AppendLine(Indent(indentLevel) + $"public static class {className}");
            sb.AppendLine(Indent(indentLevel) + "{");

            #region Fields
            sb.AppendLine(Indent(bl) + "#region Fields");
            
            sb.AppendLine(Indent(bl) + $"public const string Path = \"{EscapeString(channel.Path)}\";");
            sb.AppendLine(Indent(bl) + $"public const string ID = \"{EscapeString(channel.ID)}\";");

            sb.AppendLine();

            sb.AppendLine(Indent(bl) + "public static IAudioChannel Self => SHUU_Audio.GetChannel(Path);");
            sb.AppendLine(Indent(bl) + "public static AudioLookup Lookup => SHUU_Audio.GetLookup(Path);");
            sb.AppendLine(Indent(bl) + "public static SHUU_ObjectPool<SHUU_AudioInstance> Pool => SHUU_Audio.GetPool(Path);");

            sb.AppendLine(Indent(bl) + "#endregion");
            #endregion

            sb.AppendLine();
            sb.AppendLine();

            #region Methods
            sb.AppendLine(Indent(bl) + "#region Methods");

            sb.AppendLine(Indent(bl) + "public static SHUU_AudioInstance PlayAudio(AudioClip clip, Transform parent = null, SHUU_AudioInstance.Options options = null)");
            sb.AppendLine(Indent(bl + 1) + "=> SHUU_Audio.PlayAudio(clip, Path, parent, options);");

            sb.AppendLine();

            sb.AppendLine(Indent(bl) + "public static SHUU_AudioInstance PlayAudio(string clipName, Transform parent = null, SHUU_AudioInstance.Options options = null)");
            sb.AppendLine(Indent(bl + 1) + "=> SHUU_Audio.PlayAudio(clipName, Path, parent, options);");

            sb.AppendLine();

            sb.AppendLine(Indent(bl) + "public static SHUU_AudioInstance GetAudioInstance(Transform parent = null, SHUU_AudioInstance.Options options = null)");
            sb.AppendLine(Indent(bl + 1) + "=> SHUU_Audio.GetAudioInstance(Path, parent, options);");

            sb.AppendLine(Indent(bl) + "#endregion");
            #endregion

            #region Children
            if (channel.Children.Count > 0) sb.AppendLine(Indent(bl) + "#region Children");

            foreach (var child in channel.Children)
            {
                sb.AppendLine();
                sb.AppendLine();
                sb.AppendLine();

                BuildChannelClass(sb, child, bl);
            }

            if (channel.Children.Count > 0) sb.AppendLine(Indent(bl) + "#endregion");
            #endregion

            sb.AppendLine(Indent(indentLevel) + "}");
        }
        #endregion



        #region Helpers
		private static string Indent(int level) => new string(' ', level * 4);

		private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        #endregion

        #endregion

        #endregion




        #region Helper class
        private class ChannelInfo
        {
            public string ID;
            public string Path;
            public List<ChannelInfo> Children = new();
        }
        #endregion
    }
}
#endif
