using UnityEngine;

using SHUU.InnerWorkings.Preferences;

namespace SHUU.UserSide.Addons.AudioSystem.Preferences
{
    //[CreateAssetMenu(fileName = nameof(SHUUPreferences_AudioSystem), menuName = "SHUU/InnerWorkings/Preferences/SHUUPreferences_AudioSystem")]
    public class SHUUPreferences_AudioSystem : PreferencesBase<SHUUPreferences_AudioSystem>
    {
        #region Preferences
        public string codeGeneration_assetPath = "Assets/SHUU/AutoGenerated/AudioSystem/";
        #endregion
    }
}
