#if UNITY_EDITOR
using UnityEditor;

using SETB.InnerWorkings;

namespace SETB.UserSide.AutoGenerated
{
    public sealed class SETB_InspectorCreation_AutoGenerated
    {
        //! DO NOT MODIFY THIS CODE. IT IS AUTO GENERATED, CHANGES WILL BE OVERRIDEN.
        //! DO NOT DELETE THIS SCRIPT, IT'S NECESSARY FOR SAUB TO WORK.
		
		
		
		// <AUTO_GENERATED_START:SHUU_InspectorCreationAssets>
		[MenuItem("GameObject/SHUU/OnEveryScene", false, 48)]
		private static void OnEveryScene(MenuCommand menuCommand)
		{
			InspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex("SHUU_InspectorCreationAssets", 0, menuCommand);
		}
		[MenuItem("GameObject/SHUU/SplineCollider", false, 49)]
		private static void SplineCollider(MenuCommand menuCommand)
		{
			InspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex("SHUU_InspectorCreationAssets", 1, menuCommand);
		}
		[MenuItem("GameObject/SHUU/Audio/AudioAmbienceZone_Collider", false, 50)]
		private static void AudioAmbienceZone_Collider(MenuCommand menuCommand)
		{
			InspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex("SHUU_InspectorCreationAssets", 2, menuCommand);
		}
		[MenuItem("GameObject/SHUU/Audio/AudioAmbienceZone_Shape", false, 50)]
		private static void AudioAmbienceZone_Shape(MenuCommand menuCommand)
		{
			InspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex("SHUU_InspectorCreationAssets", 3, menuCommand);
		}
		[MenuItem("GameObject/SHUU/Audio/AudioAmbienceZone_Path", false, 50)]
		private static void AudioAmbience_Path(MenuCommand menuCommand)
		{
			InspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex("SHUU_InspectorCreationAssets", 4, menuCommand);
		}
		[MenuItem("GameObject/SHUU/UI/Chained_EventSystem", false, 51)]
		private static void Chained_EventSystem(MenuCommand menuCommand)
		{
			InspectorCreation_InnerWorkings.instance?.CreatePrefabFromIndex("SHUU_InspectorCreationAssets", 5, menuCommand);
		}
		// <AUTO_GENERATED_END:SHUU_InspectorCreationAssets>
		}
}
#endif
