using UnityEngine;
using UnityEngine.InputSystem;

namespace SHUU.InnerWorkings.Preferences
{
    //[CreateAssetMenu(fileName = nameof(SHUUPreferences_InputSystem), menuName = "SHUU/InnerWorkings/Preferences/SHUUPreferences_InputSystem")]
    public sealed class SHUUPreferences_InputSystem : PreferencesBase<SHUUPreferences_InputSystem>
    {
        #region Preferences
        [SerializeField] public InputActionAsset actionAsset;


        public string codeGeneration_assetPath = "Assets/SHUU/AutoGenerated/InputSystem/";


        public bool debugLogEmission = false;

        [SerializeField] private bool _mapDisabledWarning_debugLogEmission = false;
        public bool mapDisabledWarning_debugLogEmission => debugLogEmission && _mapDisabledWarning_debugLogEmission;     
        #endregion
    }
}
