using UnityEngine;

using SHUU.Utils.SettingsSystem;

namespace SHUU.InnerWorkings.Preferences
{
    //[CreateAssetMenu(fileName = nameof(SHUUPreferences_SettingsSystem), menuName = "SHUU/InnerWorkings/Preferences/SHUUPreferences_SettingsSystem")]
    public sealed class SHUUPreferences_SettingsSystem : PreferencesBase<SHUUPreferences_SettingsSystem>
    {
        #region Preferences
        public SettingsAtlas defaultAsset;
        public static SettingsAtlas DefaultAtlas => Instance?.defaultAsset;


        public string codeGeneration_assetPath = "Assets/SHUU/AutoGenerated/SettingsSystem/";


        public bool debugLogEmission = false;     
        #endregion
    }
}
