using System;
using System.Collections.Generic;
using UnityEngine;
using SHUU.UserSide.Addons.AudioSystem.Preferences;


#if UNITY_EDITOR
using System.IO;
using System.Text;
using UnityEditor;
#endif

using Alchemy.Inspector;

using SHUU.Utils.Data;

using static SHUU.Utils.Helpers.HandyFunctions;

using static SETB.EditorHelpers;

namespace SHUU.UserSide.Addons.AudioSystem.ScriptableObjects
{
    [CreateAssetMenu(fileName = "AudioLookup", menuName = "SHUU/Audio System/AudioLookup")]
    public class AudioLookup : ScriptableObject
    {
        #region Variables
        [SerializeField] private List<LookupItem> lookup = new();

        private Dictionary<string, LookupItem> lookupDict = new();



        // Internal
        private const string fileSuffix = "_IDs";
        private static string DefaultFilePath => SHUUPreferences_AudioSystem.Instance?.codeGeneration_assetPath;
        #endregion




        #region Main
        private void Awake()
        {
            RemoveRepeats();

            foreach (var item in lookup)
                lookupDict[item.ID] = item;
        }


        [ExecuteInEditMode, Button]
        private void RemoveRepeats()
        {
            List<string> idList = new();
            List<LookupItem> lookupCopy = new(lookup);

            foreach (var item in lookupCopy)
            {
                if (idList.Contains(item.ID))
                {
                    Debug.LogWarning($"AudioLookup: Duplicate ID found: {item.ID}. This item will be removed.");
                    lookup.Remove(item);
                }
                else idList.Add(item.ID);
            }
        }
        #endregion



        #region Logic
        public bool TryGetClip(string id, out AudioClip clip)
        {
            bool ret = lookupDict.TryGetValue(id, out var item);

            clip = item?.clip;

            return ret;
        }

        public bool TryGetClipOptionsPair(string id, out (AudioClip clip, SHUU_AudioInstance.Options options) item)
        {
            if (lookupDict.TryGetValue(id, out LookupItem lookupItem))
            {
                item = (lookupItem.clip, lookupItem.options);
                return true;
            }

            item = default;
            return false;
        }

        public bool TryGetLookupItem(string id, out LookupItem item) => lookupDict.TryGetValue(id, out item);


        public IEnumerable<string> GetAllIDs()
        {
            foreach (LookupItem item in lookup)
                yield return item.ID;
        }
        #endregion



        #region Inspector Logic
        
        #if UNITY_EDITOR
        [ExecuteInEditMode, Button]
        private void GenerateEnum()
        {
            if (lookup == null || lookup.Count == 0)
            {
                EditorUtility.DisplayDialog("Generate Audio IDs", "This AudioLookup has no entries yet — nothing to generate.", "OK");
                return;
            }

            RemoveRepeats();

            string fileName = SanitizeIdentifier($"{name}{fileSuffix}");
            string filePath = ResolveFilePath(Path.Combine(DefaultFilePath, "AudioLookupIDs"), fileName);

            DataManager.EnsureDirectoryExists(filePath);

            File.WriteAllText(filePath, BuildFile(name), new UTF8Encoding(false));

            AssetDatabase.ImportAsset(filePath);
            AssetDatabase.Refresh();
            Debug.Log($"Generated \"{filePath}\" with {lookup.Count} entr{(lookup.Count == 1 ? "y" : "ies")}.");
        }

        private string BuildFile(string className)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was auto-generated by the SHUU Audio System.");
            sb.AppendLine("// Do not edit manually — changes will be overwritten on next generation.");
            sb.AppendLine("// </auto-generated>");
            
            sb.AppendLine();
            sb.AppendLine();
            
            sb.AppendLine("namespace SHUU.UserSide.Addons.AudioSystem.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"\tpublic class SHUU_AudioLookupIDs");
            sb.AppendLine("\t{");
            sb.AppendLine($"\t\tpublic static class IDs");
            sb.AppendLine("\t\t{");
            sb.AppendLine($"\t\t\tpublic static class {className}");
            sb.AppendLine("\t\t\t{");

            var usedNames = new HashSet<string>();
            foreach (var item in lookup)
            {
                string fieldName = SanitizeToIdentifier(item.ID, usedNames);
                sb.AppendLine($"\t\t\t\tpublic const string {fieldName} = \"{item.ID}\";");
            }

            sb.AppendLine("\t\t\t}");
            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");
            sb.AppendLine("}");


            return sb.ToString();
        }


        #region Helpers
        private static string ResolveFilePath(string assetPath, string fileName)
        {
            foreach (var (_, path) in EnumerateAssetsWithPath<MonoScript>(fileName))
                if (string.Equals(Path.GetFileNameWithoutExtension(path), fileName, StringComparison.Ordinal)) return path;

            return Path.Combine(Path.GetDirectoryName(assetPath), fileName + ".cs");
        }

        private static string SanitizeToIdentifier(string id, HashSet<string> usedNames)
        {
            if (string.IsNullOrEmpty(id)) id = "Unnamed";

            var sb = new StringBuilder();
            foreach (char c in id)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');

            string result = sb.ToString();
            if (result.Length == 0 || char.IsDigit(result[0])) result = "_" + result;

            string baseName = result;
            int suffix = 1;
            while (!usedNames.Add(result))
                result = $"{baseName}_{suffix++}";

            return result;
        }
        #endregion

        #endif

        #endregion




        #region LookupItem
        [Serializable]
        public class LookupItem
        {
            #region Variables
            public string ID = "Audio_ID";

            public AudioClip clip;
            public SHUU_AudioInstance.Options options = new();
            #endregion



            #region Main
            public LookupItem()
            {
                ID = "Audio_ID";
                clip = null;
                options = new SHUU_AudioInstance.Options();
            }
            #endregion
        }
        #endregion
    }
}
